name: 🐛 Bug report
description: Report a bug or ask a question
labels: [🐛 bug]
body:
  - type: markdown
    attributes:
      value: Thanks for your interest in *Vitrea Client*!
  - type: checkboxes
    id: checks
    attributes:
      label: First Check
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I used the GitHub search to find a similar issue and didn't find it.
          required: true
  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.
      placeholder: |
        import * as Requests                     from 'vitrea-client/requests'
        import { ProtocolVersion, VitreaClient } from 'vitrea-client'

        const client = VitreaClient.create({
            host:     '192.168.1.111',
            port:     1234,
            username: 'admin',
            password: 'secret',
            version:  ProtocolVersion.V1
        })

        await client.connect()

        await client.send(new Requests.RoomCount())
      render: node
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the problem, question, or error?
    validations:
      required: true
  - type: textarea
    id: raw-data
    attributes:
      label: Raw Data
      description: Please provide the *raw* buffer data
      placeholder: 0x56, 0x54, 0x55, 0x3C, 0x2B, 0x00, 0x33, 0x78, 0x01, 0x00, 0xFF, 0x01
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Package Version
      description: |
        What version are you using?

        You can find the version by running:

        ```bash
        node -p "require('./package.json').version"
        ```
    validations:
      required: true
  - type: dropdown
    id: protocol-version
    attributes:
      label: Protocol Version
      description:  What protocol version are you using?
      options:
        - V2 (Default)
        - V1 (Legacy)
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: NodeJS Version
      description: |
        What NodeJS version are you using?

        You can find the NodeJS version by running:

        ```bash
        node --version
        ```
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
        especially if you already have a good understanding of how to implement the fix.
        Expycted is a community-managed project and we love to bring new contributors in.
      options:
        - label: Yes I am willing to submit a PR!